const canvas=document.querySelector('#board'),ctx=canvas.getContext('2d'),nctx=document.querySelector('#next').getContext('2d');
const shapes=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[0,1,1],[1,1,0]],[[1,1,0],[0,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]]],colors=['#66d8cf','#dfdf76','#ac8acb','#a8cc6d','#e88575','#799fd6','#eab577'];
let grid,piece,next,bag=[],score=0,lines=0,level=1,state='ready',last=0,acc=0,sound=false,audioCtx,best=0;
try{best=Number(localStorage.getItem('retro-tetris-best'))||0}catch(e){}document.querySelector('#best').textContent=String(best).padStart(6,'0');
function tone(freq=300,duration=.07){if(!sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='square';o.frequency.value=freq;g.gain.setValueAtTime(.035,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}catch(e){}}
function randomPiece(){if(!bag.length)bag=[0,1,2,3,4,5,6].sort(()=>Math.random()-.5);const i=bag.pop();return{m:shapes[i].map(r=>r.slice()),i,x:0,y:0}}
function fits(p,x=p.x,y=p.y,m=p.m){return m.every((r,dy)=>r.every((v,dx)=>!v||(x+dx>=0&&x+dx<10&&y+dy<20&&(y+dy<0||!grid[y+dy][x+dx]))))}
function spawn(){piece=next;next=randomPiece();piece.x=Math.floor((10-piece.m[0].length)/2);piece.y=0;if(!fits(piece))end();renderNext()}
function update(){document.querySelector('#score').textContent=String(score).padStart(6,'0');document.querySelector('#lines').textContent=String(lines).padStart(2,'0');document.querySelector('#level').textContent=String(level).padStart(2,'0');if(score>best){best=score;document.querySelector('#best').textContent=String(best).padStart(6,'0');try{localStorage.setItem('retro-tetris-best',best)}catch(e){}}}
function start(){grid=Array.from({length:20},()=>Array(10).fill(0));bag=[];score=lines=0;level=1;next=randomPiece();state='playing';acc=0;last=performance.now();spawn();update();document.querySelector('#overlay').style.display='none';document.querySelector('#status').textContent='NOW PLAYING';document.querySelector('#pause').textContent='Ⅱ 일시정지';tone(440)}
function lock(){piece.m.forEach((r,dy)=>r.forEach((v,dx)=>{if(v&&piece.y+dy>=0)grid[piece.y+dy][piece.x+dx]=piece.i+1}));const remain=grid.filter(r=>r.some(v=>!v));let count=20-remain.length;if(count){grid=[...Array.from({length:count},()=>Array(10).fill(0)),...remain];score+=[0,100,300,500,800][count]*level;lines+=count;level=1+Math.floor(lines/10);tone(650,.18)}else tone(160);update();spawn();acc=0}
function down(manual=false){if(fits(piece,piece.x,piece.y+1)){piece.y++;if(manual){score++;update()}}else lock()}
function rotate(){const m=piece.m[0].map((_,x)=>piece.m.map(r=>r[x]).reverse());for(const dx of [0,-1,1,-2,2])if(fits(piece,piece.x+dx,piece.y,m)){piece.m=m;piece.x+=dx;tone(340);break}}
function action(a){if(state!=='playing')return;if(a==='left'||a==='right'){let dx=a==='left'?-1:1;if(fits(piece,piece.x+dx))piece.x+=dx}else if(a==='rotate')rotate();else if(a==='down')down(true);else if(a==='drop'){while(fits(piece,piece.x,piece.y+1)){piece.y++;score+=2}lock();tone(210,.12)}draw()}
function overlay(title,text,button){document.querySelector('#overlay').style.display='flex';document.querySelector('#overlayTitle').textContent=title;document.querySelector('#overlayText').textContent=text;document.querySelector('#start').innerHTML=button+' <span>ENTER</span>'}
function pause(){if(state==='playing'){state='paused';overlay('PAUSED','잠시 쉬어가도 괜찮아요.','계속하기');document.querySelector('#status').textContent='PAUSED';document.querySelector('#pause').textContent='▶ 계속하기'}else if(state==='paused'){state='playing';last=performance.now();document.querySelector('#overlay').style.display='none';document.querySelector('#status').textContent='NOW PLAYING';document.querySelector('#pause').textContent='Ⅱ 일시정지'}}
function end(){state='over';overlay('GAME OVER','점수 '+score.toLocaleString()+' · 다시 도전해 보세요.','다시 시작');document.querySelector('#status').textContent='GAME OVER';tone(100,.3)}
function block(c,x,y,size,color,ghost=false){if(ghost){c.strokeStyle=color;c.globalAlpha=.4;c.lineWidth=2;c.strokeRect(x+3,y+3,size-6,size-6);c.globalAlpha=1;return}c.fillStyle=color;c.fillRect(x+1,y+1,size-2,size-2);c.fillStyle='#ffffff35';c.fillRect(x+3,y+3,size-6,3);c.fillRect(x+3,y+3,3,size-6);c.fillStyle='#00000027';c.fillRect(x+3,y+size-6,size-6,3)}
function draw(){ctx.fillStyle='#0a1013';ctx.fillRect(0,0,300,600);ctx.strokeStyle='#1a2327';ctx.lineWidth=.5;for(let x=0;x<=300;x+=30){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,600);ctx.stroke()}for(let y=0;y<=600;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(300,y);ctx.stroke()}grid.forEach((r,y)=>r.forEach((v,x)=>{if(v)block(ctx,x*30,y*30,30,colors[v-1])}));if(piece&&state!=='over'){let gy=piece.y;while(fits(piece,piece.x,gy+1))gy++;piece.m.forEach((r,y)=>r.forEach((v,x)=>{if(v){block(ctx,(piece.x+x)*30,(gy+y)*30,30,colors[piece.i],true);block(ctx,(piece.x+x)*30,(piece.y+y)*30,30,colors[piece.i])}}))}}
function renderNext(){nctx.clearRect(0,0,144,100);next.m.forEach((r,y)=>r.forEach((v,x)=>{if(v)block(nctx,(144-next.m[0].length*26)/2+x*26,(100-next.m.length*26)/2+y*26,26,colors[next.i])}))}
document.querySelector('#start').onclick=()=>state==='paused'?pause():start();document.querySelector('#pause').onclick=pause;document.querySelector('#restart').onclick=()=>{if(state==='playing'||state==='paused'){state='paused';overlay('RESTART?','현재 게임을 끝내고 새로 시작합니다.','새 게임 시작');document.querySelector('#start').onclick=()=>{start();document.querySelector('#start').onclick=()=>state==='paused'?pause():start()}}else start()};document.querySelector('#sound').onclick=()=>{sound=!sound;document.querySelector('#sound').textContent='소리 '+(sound?'ON':'OFF');document.querySelector('#sound').setAttribute('aria-pressed',sound);tone(440)};
document.addEventListener('keydown',e=>{const map={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'rotate',ArrowDown:'down',' ':'drop'};if(map[e.key]){e.preventDefault();if((e.key===' '||e.key==='ArrowUp')&&e.repeat)return;action(map[e.key])}else if(e.key==='Enter'&&state!=='playing'){e.preventDefault();document.querySelector('#start').click()}else if(e.key.toLowerCase()==='p'&&!e.repeat)pause()});
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();action(b.dataset.action)}));document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause()});
grid=Array.from({length:20},()=>Array(10).fill(0));next=randomPiece();renderNext();draw();function frame(t){if(state==='playing'){acc+=Math.min(t-last,100);if(acc>Math.max(90,850*Math.pow(.8,level-1))){down();acc=0}}last=t;draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
